config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    root 'home#index'
    resources :categories,          only: [:show]
    resources :products,            only: [:show] do
      collection do
        get :search
      end
    end
    resources :line_items,          only: [:destroy]
    resources :orders,              only: [:create, :update]
    get 'cart',                     to: 'orders#edit'
    get 'suggest',                  to: 'suggest#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_decorator.rb
Spree::Product.class_eval do
  scope :includes_price_and_images, -> {
    includes(master: [:default_price, :images])
  }

  scope :sort_products_by, -> (sort) {
    case sort
    when 'LOW_PRICE'
      except(:order).ascend_by_master_price
    when 'HIGH_PRICE'
      except(:order).descend_by_master_price
    when 'OLD_PRODUCTS'
      except(:order).order(available_on: :asc)
    else
      except(:order).order(available_on: :desc)
    end
  }

  scope :search_by, -> (search_word) {
    where('name like :search OR description like :search', search: "%#{search_word}%")
  }

  scope :related_products, -> (product) {
    in_taxons(product.taxons).where.not(id: product.id).distinct
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def auto_complete(keyword)
    require 'net/http'
    if keyword.present?
      params = URI.encode_www_form([["keyword", keyword], ["max_num", 5]])
      uri = URI.parse(Rails.application.credentials.api[:API_URL] + "?" + params)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(uri.request_uri)
      request['Authorization'] = 'Bearer ' + Rails.application.credentials.api[:API_KEY]
      response = http.request(request)
      if response.code == "200"
        JSON.parse(response.body)
      else
        []
      end
    end
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  # GET /potepan/categories/:id(.:format)
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all
    @products = Spree::Product.in_taxon(@taxon).includes_price_and_images.sort_products_by(params[:sort])
    @colors = Spree::OptionType.find_by(presentation: "Color").option_values
    @sizes = Spree::OptionType.find_by(presentation: "Size").option_values

    if params[:color]
      @products = Spree::Product.in_taxon(@taxon).with(params[:color])
    end
    if params[:size]
      @products = Spree::Product.in_taxon(@taxon).with(params[:size])
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  NEW_PRODUCTS_MAXIMUM = 8

  def index
    @new_products = Spree::Product.sort_products_by('NEW_PRODUCTS').limit(NEW_PRODUCTS_MAXIMUM).includes_price_and_images
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  # current_order
  include Spree::Core::ControllerHelpers::Order
  # current_store
  include Spree::Core::ControllerHelpers::Store
  # try_spree_current_user
  include Spree::Core::ControllerHelpers::Auth

  def destroy
    current_order.contents.remove_line_item(Spree::LineItem.find(params[:id]))
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  # current_order
  include Spree::Core::ControllerHelpers::Order
  # current_store
  include Spree::Core::ControllerHelpers::Store
  # try_spree_current_user
  include Spree::Core::ControllerHelpers::Auth
  # permitted_order_attributes
  include Spree::Core::ControllerHelpers::StrongParameters

  def edit
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
    @line_items = @order.line_items.includes(variant: [:product])
  end

  def create
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    # 2,147,483,647 is crazy. See issue https://github.com/spree/spree/issues/2695.
    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => error
      @order.errors.add(:base, error.record.errors.full_messages.join(", "))
    end

    redirect_to potepan_cart_path
  end

  def update
    @order = current_order
    if @order.contents.update_cart(order_params)
      if params.key?(:checkout) && @order.cart?
        @order.next
      elsif params.key?(:checkout)
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first) && return
      end
    end
    redirect_to potepan_cart_path
  end

  private

  def order_params
    if params[:order]
      params[:order].permit(*permitted_order_attributes)
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_MAXIMUM = 4

  # GET /potepan/products/:id(.:format)
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = Spree::Product.related_products(@product).limit(RELATED_PRODUCTS_MAXIMUM).includes_price_and_images
  end

  # GET /potepan/products/search(.:format)
  def search
    @products = Spree::Product.search_by(params[:search]).includes_price_and_images
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/suggest_controller.rb
class Potepan::SuggestController < ApplicationController
  def index
    @result = auto_complete(params[:keyword])
    respond_to do |format|
      format.json { render json: @result }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <%= render 'layouts/search_box' %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", :alt => ""), potepan_root_path, class:"navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_root_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_search_box.html.erb
<%= form_with url: search_potepan_products_path, id: "search-form", method: :get do |form| %>
  <li>
    <span class="input-group">
      <%= text_field_tag :search, "", class: "form-control searchbox", placeholder: "Search…", aria_describedby: "basic-addon2", autocomplete: "off" %>
      <span class="input-group-addon addPointer", id="basic-addon2", onclick="document.getElementById('search-form').submit();">検索</span>
    </span>
  </li>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_signup_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Single Product - BIGBAG Store</title>
    <!-- PLUGINS CSS STYLE -->
    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <!-- CUSTOM CSS -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_categories.html.erb
<div class="panel-body">
  <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
    <ul class="nav navbar-nav side-nav">
      <% taxonomies.each do |taxonomy| %>
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#category-<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
          <ul id="category-<%= taxonomy.id %>" class="collapse collapseItem">
            <% taxonomy.taxons.leaves.each do |taxon| %>
              <li>
                <%= link_to potepan_category_path(taxon.id) do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i>
                  <%= taxon.name %>
                  <span>(<%= Spree::Product.in_taxon(taxon).count %>)</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_color.html.erb
<li>
  <%= link_to potepan_category_path(color: color.name) do %>
    <%= color.presentation %>
    <span>(<%= Spree::Product.in_taxon(Spree::Taxon.find(params[:id])).with(color.name).count %>)</span>
  <% end %>
</li>

app/views/potepan/categories/_drop_down_list.html.erb
<%= form_with url: potepan_category_path(taxon.id), method: :get do |form| %>
  <%= select_tag :sort, options_for_select(
    { "新着順": "NEW_PRODUCTS",
    "安い順": "LOW_PRICE",
    "高い順": "HIGH_PRICE",
    "古い順": "OLD_PRODUCTS" },
    selected: params[:sort] ),
    { class: "select-drop", onchange: "this.form.submit()" }
  %>
<% end %>

app/views/potepan/categories/_left_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <%= render 'categories', taxonomies: taxonomies %>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <%= render partial: "color", collection: @colors %>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <%= render partial: "size", collection: @sizes %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(product.id) do %>
      <div class="productImage clearfix">
        <%= image_tag product.display_image.attachment(:large) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_size.html.erb
<li>
  <%= link_to potepan_category_path(size: size.name) do %>
    <%= size.presentation %>
    <span>(<%= Spree::Product.in_taxon(Spree::Taxon.find(params[:id])).with(size.name).count %>)</span>
  <% end %>
</li>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'light_section', taxon: @taxon %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'left_sidebar', taxonomies: @taxonomies, colors: @colors %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= render 'drop_down_list', taxon: @taxon %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: "product", collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/home/_banner.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/home/_new_product.html.erb
<div class="slide">
  <%= link_to potepan_product_path(new_product.id) do %>
    <div class="productImage clearfix">
      <%= image_tag new_product.display_image.attachment(:large) %>
    </div>
    <div class="productCaption clearfix">
      <h5><%= new_product.name %></h5>
      <h3><%= new_product.display_price %></h3>
    </div>
  <% end %>
</div>

app/views/potepan/orders/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <a href="index.html">Home</a>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item.id), { method: :delete, class: "close" } do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
      <span class="cartImage"><%= image_tag line_item.variant.display_image.attachment(:small) %></span>
    </td>
    <td class="col-xs-4"><%= line_item.variant.product.name %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2"><%= item_form.number_field :quantity, min: 0, class: "line_item_quantity" %></td>
    <td class="col-xs-2"><%= line_item.display_total %></td>
  </tr>
<% end %>

app/views/potepan/orders/_order_form.html.erb
<%= form_with(url: potepan_order_path(order), model: order, id: 'update-cart', local: true) do |order_form| %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>商品名</th>
          <th>価格</th>
          <th>数</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'line_item', collection: line_items, locals: { order_form: order_form } %>
      </tbody>
    </table>
  </div>
  <div class="updateArea">
    <%= order_form.submit 'アップデート', class: "btn" %>
  </div>
  <div class="totalAmountArea">
    <div class="col-sm-4 col-sm-offset-8 col-xs-12">
      <ul class="list-unstyled">
        <li>小計 <span><%= order.display_item_total %></span></li>
        <li>消費税 <span><%= order.display_tax_total %></span></li>
        <li>総計 <span class="grandTotal"><%= order.display_total %></span></li>
      </ul>
    </div>
  </div>
  <div class="checkBtnArea">
    <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
  </div>
<% end %>

app/views/potepan/orders/edit.html.erb
<%= render 'light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <% if @line_items.any? %>
            <%= render 'order_form', order: @order, line_items: @line_items %>
          <% else %>
            <p>カートは空です。</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_cart_form.html.erb
<%= form_with url: potepan_orders_path, method: :post, local: true do |form| %>
  <% if product.variants.any? %>
    <span class="quick-drop">
      <%= select_tag :variant_id, 
        options_from_collection_for_select(product.variants, :id, :options_text), 
        class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag :variant_id, product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select((1..5)), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag type: "submit", class: "btn btn-primary btn-block" do %>
      <i class="fa fa-angle-right" aria-hidden="true"></i>カートへ入れる
    <% end %>
  </div>
<% end%>

app/views/potepan/products/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(related_product.id) do %>
      <div class="productImage clearfix">
        <%= image_tag related_product.display_image.attachment(:large) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= related_product.name %></h5>
        <h3><%= related_product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, "Results by Search ".concat(params[:search])) %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= params[:search] %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-sm-3 col-xs-12">
          <div class="productBox">
            <%= link_to potepan_product_path(product.id) do %>
              <div class="productImage clearfix">
                <%= image_tag product.display_image.attachment(:large) %>
              </div>
              <div class="productCaption clearfix">
                <h5><%= product.name %></h5>
                <h3><%= product.display_price %></h3>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<%= render 'potepan/home/light_section' %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render 'light_section', product: @product %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <%= render 'image', product: @product %>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                <li><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</li>
              <% end %>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <%= render 'cart_form', product: @product %>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: "related_product", collection: @related_products %>
    </div>
  </div>
</section>

app/views/potepan/sample/_banner.html.erb
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>